### ISSUE TITLE
Night shift doesn't work on the TV

### ISSUE THREAD

**Issue by theodorjs** [joshjon/nocturnal#10]
I have two Mac mini. One from late 2012 that is connected to a PC monitor. Nightshift works on this one. It also shows up in the system screen settings.
The other Mac mini is from 2014, and is connected to a 4K 55" Sony Bravia TV through a Sony surround receiver. On this one nightshift doesn't show up in the system display settings, and it doesn't work in Nocturnal either. Is this to be expected, or should Nocturnal be able to override the system default compatibility?

**Comment by joshjon** [comment]
It sounds like this is expected behavior. Night shift adjustments via Nocturnal will only work if Night Shift is available through system settings. This is because it has a dependency on the Night Shift framework that ships with your machine to change the strength. On the other hand, dimness has no dependency as it simply controls a custom overlay over the screen, which is why the dimness adjustments would still work for you.

**Comment by jorisw** [comment]
I have the same problem, except for my monitor, the Night Shift panel does show up:

![image](https://user-images.githubusercontent.com/30017/80787360-a34f8e80-8b86-11ea-86f1-ff7cbca33697.png)

Can't say Nocturnal is at fault though - dragging the colour temperatur slider in this control panel, has no effect of any kind - something other Mac users have been compaining about also.
